Repository ESMCI/cime, pull requests merged in 2018-06, with the labels that each got.

#2635 Improve robustness of compare-two tests
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/CIME/test_status.py
  scripts/lib/CIME/tests/SystemTests/test_system_tests_compare_two.py
Labels: in progress

#2655 Update e3sm to compilersv2
  config/cesm/machines/config_compilers.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  scripts/fortran_unit_testing/run_tests.py
  scripts/lib/CIME/BuildTools/macrowriterbase.py
  scripts/lib/CIME/XML/compilerblock.py
  scripts/lib/CIME/XML/compilers.py
  scripts/tests/scripts_regression_tests.py
Labels: tp: CIMElib, tp: config, ty: enhancement

#2661 Import fixes and updates from e3sm
  config/e3sm/machines/config_compilers.xml
Labels: tp: config, ty: Bug Fix

#2665 Allow users to go up through the setup phase on non-local machines
  scripts/create_newcase
  scripts/create_test
  scripts/lib/CIME/XML/compilers.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/test_scheduler.py
  src/drivers/mct/cime_config/config_component.xml
Labels: tp: CIMElib, tp: script tools, ty: enhancement

#2662 Edit and cleanup parts of CCS users guide
  doc/source/users_guide/building-a-case.rst
  doc/source/users_guide/cime-change-namelist.rst
  doc/source/users_guide/cime-dir.rst
  doc/source/users_guide/compsets.rst
  doc/source/users_guide/create-a-case.rst
  doc/source/users_guide/index.rst
  doc/source/users_guide/introduction-and-overview.rst
  doc/source/users_guide/pes-threads.rst
  doc/source/users_guide/running-a-case.rst
  doc/source/users_guide/setting-up-a-case.rst
Labels: in progress

#2670 XSD definitions did not match implementation
  config/e3sm/machines/config_batch.xml
  config/xml_schemas/config_batch.xsd
Labels: in progress, ty: Bug Fix

#2675 Bluewaters update
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress

#2684 fix issue with rebuilding csm_share
  scripts/Tools/Makefile
  src/build_scripts/buildlib.csm_share
Labels: in progress

#2683 fix issue with e3sm mali file archiving
  scripts/lib/CIME/case/case_st_archive.py
Labels: in progress

#2690 Maint 5.6
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  doc/source/users_guide/building-a-case.rst
  doc/source/users_guide/cime-change-namelist.rst
  doc/source/users_guide/cime-dir.rst
  doc/source/users_guide/compsets.rst
  doc/source/users_guide/create-a-case.rst
  doc/source/users_guide/index.rst
  doc/source/users_guide/introduction-and-overview.rst
  doc/source/users_guide/pes-threads.rst
  doc/source/users_guide/running-a-case.rst
  doc/source/users_guide/setting-up-a-case.rst
  scripts/Tools/Makefile
  scripts/lib/CIME/XML/env_batch.py
  src/build_scripts/buildlib.csm_share
Labels: in progress

#2689 Jgfouca/branch for acme split 2018 06 25
  config/e3sm/allactive/config_compsets.xml
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/config_pio.xml
  config/e3sm/machines/template.st_archive
  config/e3sm/testmods_dirs/allactive/mach/pet/shell_commands
  config/e3sm/testmods_dirs/allactive/v1cmip6/shell_commands
  config/e3sm/tests.py
  scripts/lib/CIME/SystemTests/homme.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/case/preview_namelists.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/utils.py
  src/drivers/mct/cime_config/config_component_e3sm.xml
Labels: in progress

#2680 Use ConfigParser rather than SafeConfigParser
  scripts/Tools/case.submit
  scripts/tests/scripts_regression_tests.py
Labels: in progress

#2692 Fix for passing run arguments in LSF
  config/e3sm/machines/config_batch.xml
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress

#2691 Compsets
  scripts/lib/CIME/XML/compsets.py
Labels: in progress

#2694 add return_values to machines.py for XML to HTML machine script
  scripts/lib/CIME/XML/machines.py
Labels: in progress, ty: enhancement

#2674 Cmake build
  CMakeLists.txt
  config/cesm/machines/config_compilers.xml
  pio_config.cmake.in
  scripts/cmake/includedCMakeLists.txt
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/case/preview_namelists.py
  src/CMake/CIME_initial_setup.cmake
  src/CMake/genf90_utils.cmake
  src/components/stub_comps/satm/CMakeLists.txt
  src/components/stub_comps/sesp/CMakeLists.txt
  src/components/stub_comps/sglc/CMakeLists.txt
  src/components/stub_comps/sice/CMakeLists.txt
  src/components/stub_comps/slnd/CMakeLists.txt
  src/components/stub_comps/socn/CMakeLists.txt
  src/components/stub_comps/srof/CMakeLists.txt
  src/components/stub_comps/swav/CMakeLists.txt
  src/components/xcpl_comps/xatm/CMakeLists.txt
  src/components/xcpl_comps/xglc/CMakeLists.txt
  src/components/xcpl_comps/xice/CMakeLists.txt
  src/components/xcpl_comps/xlnd/CMakeLists.txt
  src/components/xcpl_comps/xocn/CMakeLists.txt
  src/components/xcpl_comps/xrof/CMakeLists.txt
  src/components/xcpl_comps/xshare/CMakeLists.txt
  src/components/xcpl_comps/xwav/CMakeLists.txt
  src/drivers/mct/shr/CMakeLists.txt
  src/externals/pio1/pio/CMakeLists.txt
  src/share/timing/CMakeLists.txt
  src/share/util/#CMakeLists.txt#
  src/share/util/CMakeLists.txt
Labels: in progress

#2696 Automatically handle easy conflicts in e3sm cime management
  scripts/lib/e3sm_cime_mgmt.py
Labels: e3sm-only, in progress, tp: script tools, ty: enhancement
