Repository ESMCI/cime, pull requests merged in 2018-07, with the labels that each got.

#2701 Maint 5.6 hobart update
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  config/xml_schemas/config_machines.xsd
  scripts/Tools/Makefile
Labels: in progress

#2697 Maint 5.6 nersc update
  config/cesm/machines/config_machines.xml
  scripts/Tools/preview_run
  scripts/lib/CIME/case/case.py
Labels: in progress

#2702 dont adjust specificity if attribute on field
  scripts/lib/CIME/XML/compilerblock.py
Labels: in progress

#2703 More fixes and tests for V2 compiler macro system
  scripts/lib/CIME/BuildTools/macroconditiontree.py
  scripts/lib/CIME/BuildTools/valuesetting.py
  scripts/lib/CIME/XML/compilerblock.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress, tp: CIMElib, ty: Bug Fix, ty: enhancement

#2704 Jgfouca/branch for acme split 2018 07 06
  config/e3sm/allactive/config_compsets.xml
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/config_files.xml
  config/e3sm/machines/config_pio.xml
  config/e3sm/tests.py
  scripts/lib/CIME/XML/compilerblock.py
  scripts/lib/CIME/case/case_run.py
Labels: in progress

#2709 Fix for cprnc on hobart
  config/cesm/machines/config_machines.xml
Labels: in progress

#2693 Make docs more consistent
  doc/source/users_guide/create-a-case.rst
  scripts/create_newcase
Labels: in progress, tp: documentation, ty: enhancement

#2711 Jgfouca/branch for acme split 2018 07 11
  config/e3sm/tests.py
Labels: in progress

#2710 Rework machine overrides in config_compilers.
  scripts/lib/CIME/BuildTools/macroconditiontree.py
  scripts/lib/CIME/BuildTools/possiblevalues.py
  scripts/lib/CIME/BuildTools/valuesetting.py
  scripts/lib/CIME/XML/compilerblock.py
  scripts/lib/CIME/XML/compilers.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress

#2712 Turn off auto conflict resolution by default for e3sm cime mgmt tools
  scripts/Tools/e3sm_cime_merge
  scripts/Tools/e3sm_cime_split
  scripts/lib/e3sm_cime_mgmt.py
Labels: e3sm-only, in progress, tp: script tools

#2714 Correct DIN_LOC_ROOT_CLMFORC for new glade configuration on cheyenne
  config/cesm/machines/config_machines.xml
Labels: in progress

#2715 Maint 5.6 archive_metadata
  scripts/Tools/archive_metadata
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/utils.py
Labels: cesm-only, in progress, maint-5.6_bugfix, tp: script tools, ty: enhancement

#2720 improve compiler not support msg
  scripts/lib/CIME/XML/compilers.py
Labels: tp: CIMElib, ty: enhancement

#2700 fix wget option for directories
  scripts/lib/CIME/Servers/wget.py
Labels: in progress

#2727 more theta updates
  config/cesm/machines/config_machines.xml
Labels: cesm-only, machine specific

#2733 ESMF logging fix
  src/drivers/mct/cime_config/config_component.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/cime_driver.F90
  src/drivers/mct/shr/seq_comm_mct.F90
  src/share/esmf_wrf_timemgr/ESMF_Stubs.F90
Labels: maint-5.6_bugfix, ty: Bug Fix
