Repository ESMCI/cime, pull requests merged in 2018-11, with the labels that each got.

#2900 archive_metadata add Total Time parsing for timeseries and xconform
  scripts/Tools/archive_metadata
Labels: cesm-only, in progress, ty: enhancement

#2902 Misomip
  config/cesm/config_grids.xml
  src/drivers/mct/shr/seq_flds_mod.F90
Labels: in progress

#2905 Update to pyCECT v3.0.8
  tools/statistical_ensemble_test/pyCECT/README_pyCECT.rst
  tools/statistical_ensemble_test/pyCECT/README_pyEnsSum.rst
  tools/statistical_ensemble_test/pyCECT/README_pyEnsSumPop.rst
  tools/statistical_ensemble_test/pyCECT/pyCECT.py
  tools/statistical_ensemble_test/pyCECT/pyEnsLib.py
  tools/statistical_ensemble_test/pyCECT/pyEnsSum.py
  tools/statistical_ensemble_test/pyCECT/pyEnsSumPop.py
  tools/statistical_ensemble_test/pyCECT/pyEnsSumPop_test.sh
  tools/statistical_ensemble_test/pyCECT/test_pop_CECT.sh
  tools/statistical_ensemble_test/pyCECT/test_pop_ensemble.sh
  tools/statistical_ensemble_test/pyCECT/test_pyEnsSumPop.sh
Labels: in progress

#2914 Do not include time of day in cpl auxiliary hist file names
  src/drivers/mct/main/seq_hist_mod.F90
Labels: in progress, maint-5.6_bugfix, tp: drv mct, ty: Bug Fix

#2919 Update addmetadata for POP-ECT tests
  tools/statistical_ensemble_test/addmetadata.sh
Labels: in progress

#2920 Fix new pylint errs
  scripts/lib/CIME/BuildTools/macrowriterbase.py
  scripts/lib/CIME/SystemTests/erio.py
  scripts/lib/CIME/SystemTests/ers.py
  scripts/lib/CIME/SystemTests/ers2.py
  scripts/lib/CIME/SystemTests/homme.py
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/case/case_st_archive.py
  scripts/lib/CIME/provenance.py
  scripts/lib/e3sm_cime_mgmt.py
  src/build_scripts/buildlib.gptl
  src/build_scripts/buildlib.pio
Labels: in progress

#2921 fix new pylint errors
  scripts/lib/CIME/BuildTools/macrowriterbase.py
  scripts/lib/CIME/SystemTests/erio.py
  scripts/lib/CIME/SystemTests/ers.py
  scripts/lib/CIME/SystemTests/ers2.py
  scripts/lib/CIME/SystemTests/homme.py
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/case/case_st_archive.py
  scripts/lib/CIME/provenance.py
  scripts/lib/e3sm_cime_mgmt.py
  src/build_scripts/buildlib.gptl
  src/build_scripts/buildlib.pio
Labels: in progress

#2926 Jgfouca/branch for acme split 2018 11 27
  config/e3sm/allactive/config_compsets.xml
  config/e3sm/config_grids.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/tests.py
  scripts/Tools/Makefile
  scripts/Tools/cime_bisect
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/get_timing.py
  scripts/lib/CIME/utils.py
  src/components/data_comps/datm/cime_config/namelist_definition_datm.xml
  src/components/data_comps/drof/cime_config/config_component.xml
  src/components/data_comps/drof/cime_config/namelist_definition_drof.xml
  src/drivers/mct/cime_config/config_component_e3sm.xml
  src/drivers/mct/main/seq_diag_mct.F90
  src/drivers/mct/shr/seq_flds_mod.F90
  src/share/timing/ChangeLog
  src/share/timing/f_wrappers.c
  src/share/timing/gptl.c
  src/share/timing/gptl.h
  src/share/timing/gptl.inc
  src/share/timing/perf_mod.F90
  tools/configure
Labels: in progress
