Repository ESMCI/cime, pull requests merged in 2018-05, with the labels that each got.

#2520 update load balance tool
  tools/load_balancing_tool/load_balancing_submit.py
  tools/load_balancing_tool/tests/load_balancing_test.py
Labels: in progress

#2525 refine distinction of E vs Q compset
  scripts/lib/CIME/case/case.py
Labels: in progress

#2534 Convert more unsafe copies to safe.
  src/build_scripts/buildlib.pio
  src/components/data_comps/datm/cime_config/buildnml
  src/components/data_comps/desp/cime_config/buildnml
  src/components/data_comps/dice/cime_config/buildnml
  src/components/data_comps/dlnd/cime_config/buildnml
  src/components/data_comps/docn/cime_config/buildnml
  src/components/data_comps/drof/cime_config/buildnml
  src/components/data_comps/dwav/cime_config/buildnml
  src/drivers/mct/cime_config/buildnml
Labels: tp: CIMElib, tp: script tools, ty: enhancement

#2536 Add ability to skip checks of some locked env files.
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/check_lockedfiles.py
Labels: tp: CIMElib, ty: enhancement

#2539 Upgrade preview_run.
  scripts/Tools/preview_run
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/utils.py
Labels: tp: CIMElib, tp: script tools, ty: enhancement

#2555 Fix some queue stuff that got broken recently
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case/case_setup.py
  scripts/tests/scripts_regression_tests.py
Labels: tp: CIMElib, ty: Bug Fix

#2549 Convert e3sm grids
  config/cesm/machines/config_machines.xml
  config/e3sm/allactive/config_compsets.xml
  config/e3sm/config_grids.xml
  scripts/Tools/xmlconvertors/convert-grid-v1-to-v2
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/XML/grids.py
Labels: e3sm-only, tp: config, tp: tools

#2579 Update model_version
  src/drivers/mct/cime_config/namelist_definition_drv.xml
Labels: tp: user interface, ty: Bug, user interface

#2585 Documentation updates, including major updates to --help for scripts
  doc/source/conf.py
  doc/source/users_guide/building-a-case.rst
  doc/source/users_guide/cime-config.rst
  doc/source/users_guide/cloning-a-case.rst
  doc/source/users_guide/porting-cime.rst
  doc/source/users_guide/running-a-case.rst
  doc/source/users_guide/testing.rst
  scripts/Tools/case.build
  scripts/Tools/case.cmpgen_namelists
  scripts/Tools/case.qstatus
  scripts/Tools/case.setup
  scripts/Tools/case.submit
  scripts/Tools/check_case
  scripts/Tools/check_input_data
  scripts/Tools/preview_namelists
  scripts/Tools/preview_run
  scripts/Tools/xmlchange
  scripts/Tools/xmlquery
  scripts/create_clone
  scripts/create_newcase
  scripts/create_test
  scripts/lib/CIME/utils.py
  scripts/query_config
  scripts/query_testlists
Labels: tp: documentation, tp: user interface

#2582 a new script to add additional metadata for stat ensemble test
  tools/statistical_ensemble_test/README
  tools/statistical_ensemble_test/addmetadata.sh
Labels: tp: tools, ty: enhancement

#2600 multisubmit tests were not resubmitting.
  config/cesm/machines/template.case.test
  config/cesm/machines/template.st_archive
  scripts/lib/CIME/SystemTests/pet.py
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/case/case_st_archive.py
Labels: maint-5.6_bugfix

#2602 In datm, set orbital parameters in run loop
  src/components/data_comps/datm/datm_comp_mod.F90
  src/components/data_comps/datm/mct/atm_comp_mct.F90
Labels: maint-5.6_bugfix, tp: data models, ty: Bug Fix

#2601 statistical ens. test (python scripts)
  tools/statistical_ensemble_test/README
  tools/statistical_ensemble_test/ensemble.py
  tools/statistical_ensemble_test/single_run.py
Labels: tp: tools, ty: enhancement

#2608 move cam section out of config archive
  config/cesm/config_archive.xml
Labels: maint-5.6_bugfix

#2614 Maint 5.6 - documentation updates
  .gitignore
  config/cesm/machines/template.case.run
  config/cesm/machines/template.case.test
  config/cesm/machines/template.st_archive
  doc/Makefile
  doc/README
  doc/source/README
  doc/tools_autodoc.cfg
  doc/tools_autodoc.py
  scripts/Tools/xmlquery
  scripts/manage_pes
Labels: tp: documentation

#2615 Mvertens/more doc updates
  doc/source/users_guide/building-a-case.rst
  doc/source/users_guide/cime-change-namelist.rst
  doc/source/users_guide/cloning-a-case.rst
  doc/source/users_guide/compsets.rst
  doc/source/users_guide/create-a-case.rst
  doc/source/users_guide/grids.rst
  doc/source/users_guide/index.rst
  doc/source/users_guide/introduction-and-overview.rst
  doc/source/users_guide/machine.rst
  doc/source/users_guide/pes-threads.rst
  doc/source/users_guide/porting-cime.rst
  doc/source/users_guide/running-a-case.rst
  doc/source/users_guide/setting-up-a-case.rst
  doc/source/users_guide/testing.rst
  doc/source/users_guide/timers.rst
  doc/source/users_guide/troubleshooting.rst
  doc/source/users_guide/unit_testing.rst
  doc/source/users_guide/use_cases/basics-a-basic-example.rst
  doc/source/users_guide/use_cases/basics-setting-up-a-branch-or-hybrid-run.rst
  doc/source/users_guide/use_cases/cesm-nml.rst
  doc/source/users_guide/use_cases/datamod-nml.rst
  doc/source/users_guide/use_cases/driver-nml.rst
  doc/source/users_guide/use_cases/namelist-gen.rst
  doc/source/users_guide/use_cases/use-cases.rst
  doc/source/users_guide/workflows.rst
Labels: tp: documentation

#2616 update for Sphinx v1.7 and doc version 5.6
  doc/README
  doc/source/conf.py
Labels: tp: documentation

#2627 Maint 5.6
  .gitignore
  ChangeLog
  config/cesm/config_archive.xml
  config/cesm/config_grids.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  config/cesm/machines/template.case.run
  config/cesm/machines/template.case.test
  config/cesm/machines/template.st_archive
  doc/Makefile
  doc/README
  doc/source/README
  doc/source/conf.py
  doc/source/users_guide/building-a-case.rst
  doc/source/users_guide/cime-change-namelist.rst
  doc/source/users_guide/cloning-a-case.rst
  doc/source/users_guide/compsets.rst
  doc/source/users_guide/create-a-case.rst
  doc/source/users_guide/grids.rst
  doc/source/users_guide/index.rst
  doc/source/users_guide/introduction-and-overview.rst
  doc/source/users_guide/machine.rst
  doc/source/users_guide/pes-threads.rst
  doc/source/users_guide/porting-cime.rst
  doc/source/users_guide/running-a-case.rst
  doc/source/users_guide/setting-up-a-case.rst
  doc/source/users_guide/testing.rst
  doc/source/users_guide/timers.rst
  doc/source/users_guide/troubleshooting.rst
  doc/source/users_guide/unit_testing.rst
  doc/source/users_guide/use_cases/basics-a-basic-example.rst
  doc/source/users_guide/use_cases/basics-setting-up-a-branch-or-hybrid-run.rst
  doc/source/users_guide/use_cases/cesm-nml.rst
  doc/source/users_guide/use_cases/datamod-nml.rst
  doc/source/users_guide/use_cases/driver-nml.rst
  doc/source/users_guide/use_cases/namelist-gen.rst
  doc/source/users_guide/use_cases/use-cases.rst
  doc/source/users_guide/workflows.rst
  doc/tools_autodoc.cfg
  doc/tools_autodoc.py
  scripts/create_newcase
  scripts/create_test
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/XML/machines.py
  scripts/lib/CIME/compare_namelists.py
  scripts/lib/CIME/utils.py
  scripts/manage_pes
  scripts/tests/scripts_regression_tests.py
  src/components/data_comps/datm/datm_comp_mod.F90
  src/components/data_comps/datm/mct/atm_comp_mct.F90
  src/drivers/mct/cime_config/testdefs/testlist_drv.xml
  src/externals/pio1/pio/box_rearrange.F90.in
  src/externals/pio1/pio/pio_support.F90
  src/externals/pio1/pio/piolib_mod.F90
  tools/statistical_ensemble_test/README
  tools/statistical_ensemble_test/ensemble.py
  tools/statistical_ensemble_test/single_run.py
Labels: in progress

#2628 Mvertens/more doc updates
  doc/source/users_guide/pes-threads.rst
  doc/source/users_guide/timers.rst
  doc/source/users_guide/workflows.rst
Labels: tp: documentation

#2630 Fix find_circular_dependency.py
  tools/utils/find_circular_dependency.py
Labels: in progress, ty: Bug Fix

#2634 Update pyCECT to 3.0.7
  tools/statistical_ensemble_test/pyCECT/.gitignore
  tools/statistical_ensemble_test/pyCECT/EET.py
  tools/statistical_ensemble_test/pyCECT/LICENSE.txt
  tools/statistical_ensemble_test/pyCECT/README_pyCECT.rst
  tools/statistical_ensemble_test/pyCECT/README_pyEnsSum.rst
  tools/statistical_ensemble_test/pyCECT/ens_excluded_varlist.json
  tools/statistical_ensemble_test/pyCECT/ens_sub.pbs
  tools/statistical_ensemble_test/pyCECT/ens_sub.sh
  tools/statistical_ensemble_test/pyCECT/exclude_empty.json
  tools/statistical_ensemble_test/pyCECT/included_varlist.json
  tools/statistical_ensemble_test/pyCECT/pyCECT.py
  tools/statistical_ensemble_test/pyCECT/pyEnsLib.py
  tools/statistical_ensemble_test/pyCECT/pyEnsSum.py
  tools/statistical_ensemble_test/pyCECT/pyEnsSumPop.py
Labels: in progress
