Repository ESMCI/cime, pull requests merged in 2018-10, with the labels that each got.

#2823 fix inputdata issue for multi_instance cases
  scripts/Tools/archive_metadata
  scripts/lib/CIME/nmlgen.py
  src/components/data_comps/datm/cime_config/buildnml
  src/components/data_comps/desp/cime_config/buildnml
  src/components/data_comps/dice/cime_config/buildnml
  src/components/data_comps/dlnd/cime_config/buildnml
  src/components/data_comps/docn/cime_config/buildnml
  src/components/data_comps/drof/cime_config/buildnml
  src/components/data_comps/dwav/cime_config/buildnml
Labels: in progress

#2782 Attach the instance number to 'cpl' in cpl history file names,
  scripts/create_newcase
  scripts/lib/CIME/case/case.py
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/seq_hist_mod.F90
Labels: in progress, maint-5.6_bugfix, ty: Bug Fix

#2824 Better format for seq_flds_YYY_{fluxes,states} log messages
  src/drivers/mct/shr/seq_flds_mod.F90
Labels: in progress, maint-5.6_bugfix, ty: Bug Fix

#2825 Improve continue run checks in case_submit
  scripts/lib/CIME/case/case_submit.py
  scripts/lib/CIME/utils.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2828 Update presaero and CO2 datasets for datm7 to new CMIP6 version
  src/components/data_comps/datm/cime_config/config_component.xml
  src/components/data_comps/datm/cime_config/namelist_definition_datm.xml
Labels: cesm-only, imp: Climate Changing, imp: non-BFB, in progress, maint-5.6_bugfix, tp: data models, tp: user interface, ty: enhancement

#2826 Add FUNIT fake test
  config/config_tests.xml
  scripts/lib/CIME/SystemTests/funit.py
Labels: in progress

#2834 Dont hide ctest output in run_tests.py
  scripts/fortran_unit_testing/run_tests.py
Labels: in progress, tp: CIMElib, tp: script tools, ty: Bug Fix

#2829 xmlchange: Give user guidance on what to do next
  scripts/Tools/xmlchange
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_setup.py
Labels: in progress, tp: CIMElib, tp: script tools, ty: enhancement

#2833 Propagate logging settings to submitted jobs
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2837 change default for flux_convergence for all but 1 degree case
  src/drivers/mct/cime_config/buildnml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
Labels: in progress

#2839 remove overzelous debug code
  src/share/streams/shr_stream_mod.F90
Labels: in progress

#2842 backport pr 2833 to maint-5.6
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress

#2832 hr2x at endofrun
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/main/cime_comp_mod.F90
Labels: in progress, maint-5.6_bugfix, tp: drv mct, ty: Bug Fix

#2840 User nl error msg
  .travis.yml
  config/cesm/machines/config_machines.xml
  scripts/Tools/archive_metadata
  scripts/create_newcase
  scripts/lib/CIME/XML/batch.py
  scripts/lib/CIME/XML/compilers.py
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/XML/machines.py
  scripts/lib/CIME/XML/namelist_definition.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress

#2843 improve case clone functionality
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_clone.py
Labels: in progress

#2847 Maint 5.6 merge
  .travis.yml
  ChangeLog
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  scripts/Tools/archive_metadata
  scripts/create_newcase
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/XML/machines.py
  scripts/lib/CIME/XML/namelist_definition.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/nmlgen.py
  scripts/lib/CIME/utils.py
  scripts/tests/scripts_regression_tests.py
  src/components/data_comps/datm/cime_config/buildnml
  src/components/data_comps/datm/cime_config/config_component.xml
  src/components/data_comps/datm/cime_config/namelist_definition_datm.xml
  src/components/data_comps/desp/cime_config/buildnml
  src/components/data_comps/dice/cime_config/buildnml
  src/components/data_comps/dlnd/cime_config/buildnml
  src/components/data_comps/docn/cime_config/buildnml
  src/components/data_comps/drof/cime_config/buildnml
  src/components/data_comps/dwav/cime_config/buildnml
  src/drivers/mct/cime_config/buildnml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/seq_hist_mod.F90
  src/drivers/mct/shr/seq_flds_mod.F90
  src/drivers/mct/shr/seq_infodata_mod.F90
  src/share/streams/shr_stream_mod.F90
Labels: in progress

#2849 cleanup and reorder xml files
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  scripts/lib/CIME/case/case_clone.py
Labels: in progress

#2838 add ability for testfile to contain comments
  scripts/create_test
Labels: in progress

#2844 improve clean function
  scripts/fortran_unit_testing/run_tests.py
  src/CMake/FindpFUnit.cmake
Labels: in progress

#2845 Improve idmap test
  scripts/lib/CIME/nmlgen.py
  src/drivers/mct/cime_config/buildnml
  src/drivers/mct/cime_config/config_component.xml
Labels: in progress

#2804 Don't exceed maximum MPI tag value
  src/drivers/mct/main/component_mod.F90
Labels: in progress, tp: drv mct, ty: Bug Fix

#2853 response to review comments of pr 2844 and remove user-grid option
  scripts/create_newcase
  scripts/fortran_unit_testing/run_tests.py
Labels: in progress

#2857 add the list of supported mpilibs to the --machine output
  scripts/query_config
Labels: in progress

#2859 Fix floating-point mpiprocs for Python 3
  scripts/lib/CIME/XML/env_mach_pes.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2858 Jgfouca/branch for acme split 2018 10 16
  config/config_tests.xml
  config/e3sm/config_grids.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/tests.py
  scripts/Tools/jenkins_generic_job
  scripts/lib/CIME/SystemTests/mvk.py
  scripts/lib/CIME/SystemTests/pgn.py
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/tsc.py
  scripts/lib/CIME/code_checker.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/test_status.py
  src/components/data_comps/docn/cime_config/config_component.xml
  src/externals/pio2/cmake/FindNetCDF.cmake
Labels: in progress

#2860 compute tasks_per_node via floor division
  scripts/lib/CIME/XML/env_mach_pes.py
Labels: in progress

#2862 Remove reference to deleted testmods directories
  doc/source/users_guide/testing.rst
Labels: in progress

#2865 Maint 5.6 archive_metadata
  scripts/Tools/archive_metadata
Labels: cesm-only, in progress, tp: script tools

#2864 Updates to CIME statistical ensemble test ensemble generation scripts
  tools/statistical_ensemble_test/README
  tools/statistical_ensemble_test/ensemble.py
  tools/statistical_ensemble_test/ensemble.sh
  tools/statistical_ensemble_test/single_run.py
  tools/statistical_ensemble_test/single_run.sh
Labels: in progress

#2866 Set update
  tools/statistical_ensemble_test/README
  tools/statistical_ensemble_test/ensemble.py
  tools/statistical_ensemble_test/ensemble.sh
  tools/statistical_ensemble_test/single_run.py
  tools/statistical_ensemble_test/single_run.sh
Labels: in progress

#2869 Bug fix
  src/components/xcpl_comps/xshare/mct/dead_mct_mod.F90
Labels: tp: drv mct, ty: Bug Fix

#2868 Remove all references to BATCHQUERY and BATCHSUBMIT
  config/e3sm/machines/config_machines.xml
  scripts/lib/CIME/case/case_run.py
Labels: in progress, tp: CIMElib

#2854 Require < mpirun > and < module_system > in machine config
  config/e3sm/config_files.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/config_pio.xml
  config/xml_schemas/config_machines.xsd
  scripts/lib/CIME/case/case.py
Labels: in progress

#2873 Altuntas/mom6 misomip
  config/cesm/config_grids.xml
  config/cesm/machines/config_compilers.xml
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/prep_glc_mod.F90
  src/drivers/mct/shr/seq_flds_mod.F90
Labels: in progress

#2875 Altuntas/mom6 misomip
  config/cesm/config_grids.xml
  src/drivers/mct/shr/seq_flds_mod.F90
Labels: in progress

#2877 Sarich/update e3sm config driver
  config/e3sm/config_files.xml
  src/drivers/nuopc/cime_config/namelist_definition_drv.xml
Labels: in progress

#2876 Fix PET on no-batch machines
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/tests/SystemTests/test_system_tests_compare_two.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2882 resolve mpi run command
  scripts/lib/CIME/case/case.py
Labels: in progress

#2883 Add config_component_e3sm.xml for nuopc
  src/drivers/nuopc/cime_config/config_component_e3sm.xml
Labels: in progress, tp: config, ty: Bug Fix

#2884 fine tuning for CMIP6 cases
  scripts/Tools/archive_metadata
Labels: cesm-only, in progress, tp: script tools, ty: enhancement

#2872 Fix typo in setting strm_datdir for CLM_QIAN_WISO.TPQW
  src/components/data_comps/datm/cime_config/namelist_definition_datm.xml
Labels: in progress, tp: data models, ty: Bug Fix

#2887 FUNIT test: Fix path to run_tests.py if get_test_spec_dir is overridden
  scripts/lib/CIME/SystemTests/funit.py
Labels: in progress, tp: system tests, ty: Bug Fix

#2892 Remove redundant check of mpi-tag values
  scripts/lib/get_tests.py
  src/drivers/mct/main/component_mod.F90
Labels: in progress, tp: drv mct, ty: Bug Fix

#2895 Update lnd2glc_averaged_now in the driver loop
  src/drivers/mct/main/cime_comp_mod.F90
Labels: in progress, tp: drv mct, ty: Bug Fix

#2897 Fix regex matches in hist_utils: get_extension
  scripts/lib/CIME/hist_utils.py
Labels: in progress, tp: CIMElib, ty: Bug Fix
