Repository ESMCI/cime, pull requests merged in 2018-04, with the labels that each got.

#2415 St_archive the DART restart history files
  config/cesm/config_archive.xml
  scripts/lib/CIME/case/case_st_archive.py
Labels: tp: config, tp: user interface, ty: enhancement

#2410 Always downscale walltime for tests
  config/e3sm/machines/config_batch.xml
  scripts/lib/CIME/XML/env_batch.py
Labels: tp: CIMElib, ty: enhancement

#2397 Update MPI message tags in coupler-component exchanges
  src/drivers/mct/main/component_mod.F90
  src/share/util/shr_flux_mod.F90
Labels: in progress, tp: drv mct, tp: src shr, ty: Bug Fix

#2417 improve cprnc build
  tools/cprnc/Makefile
Labels: in progress

#2412 allow envvars to be unresolved
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_run.py
Labels: tp: CIMElib, ty: Bug Fix

#2362 Update hobart queue limits
  config/cesm/machines/config_batch.xml
Labels: in progress

#2419 Restore shell batch capability
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case/case_setup.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2422 Cesm test fixes
  config/cesm/config_archive.xml
  scripts/Tools/mkSrcfiles
  scripts/lib/CIME/SystemTests/eri.py
  scripts/lib/CIME/SystemTests/erp.py
  scripts/lib/CIME/SystemTests/ers.py
  scripts/lib/CIME/SystemTests/nck.py
  scripts/lib/CIME/SystemTests/seq.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  src/share/util/shr_scam_mod.F90
Labels: in progress

#2423 more cesm testing changes
  config/cesm/config_archive.xml
  scripts/lib/CIME/SystemTests/eri.py
  scripts/lib/CIME/SystemTests/ers.py
Labels: in progress

#2424 fix skip_pnl issues
  scripts/lib/CIME/SystemTests/eri.py
  scripts/lib/CIME/SystemTests/ers.py
Labels: in progress

#2425 cime_bisect improvements
  scripts/Tools/cime_bisect
Labels: in progress, tp: script tools, ty: enhancement

#2426 more fixes for archiver and tests
  config/cesm/config_archive.xml
  scripts/lib/CIME/SystemTests/eri.py
  scripts/lib/CIME/SystemTests/irt.py
  scripts/lib/CIME/SystemTests/nck.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/case/case_st_archive.py
  src/drivers/mct/cime_config/config_archive.xml
Labels: in progress

#2432 Fixes the potential leak reported by address sanitizer in PIO
  src/externals/pio1/pio/piodarray.F90.in
Labels: in progress

#2434 Revert small piece of #2299
  src/drivers/mct/shr/seq_comm_mct.F90
Labels: in progress, tp: drv mct, ty: Bug Fix

#2437 two more places we need to call case_setup
  scripts/lib/CIME/SystemTests/pea.py
  scripts/lib/CIME/SystemTests/pem.py
Labels: in progress

#2433 E3SM split
  ChangeLog
  config/e3sm/allactive/config_compsets.xml
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/config_archive.xml
  config/e3sm/config_files.xml
  config/e3sm/machines/Depends.summit.ibm
  config/e3sm/machines/Depends.theta.intel
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/testmods_dirs/allactive/cam/cosplite/user_nl_cam
  config/e3sm/testmods_dirs/allactive/cam/cosplite/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/cam/cosplite_nhtfrq5/user_nl_cam
  config/e3sm/testmods_dirs/allactive/cam/cosplite_nhtfrq5/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/cam/outfrq9s/user_nl_cam
  config/e3sm/testmods_dirs/allactive/cam/outfrq9s/user_nl_clm
  config/e3sm/testmods_dirs/allactive/cam/outfrq9s/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/cam/rtm_null/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/clm/betr/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/clm/bgcexp/user_nl_clm
  config/e3sm/testmods_dirs/allactive/clm/bgcexp/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/clm/bgcinterface/user_nl_clm
  config/e3sm/testmods_dirs/allactive/clm/eca/user_nl_clm
  config/e3sm/testmods_dirs/allactive/clm/fates/user_nl_clm
  config/e3sm/testmods_dirs/allactive/clm/rd/user_nl_clm
  config/e3sm/testmods_dirs/allactive/clm/vst/user_nl_clm
  config/e3sm/testmods_dirs/allactive/drv/y100k
  config/e3sm/testmods_dirs/allactive/force_netcdf_pio/xmlchange_cmnds
  config/e3sm/testmods_dirs/allactive/v1cmip6/shell_commands
  config/e3sm/testmods_dirs/allactive/v1cmip6/xmlchange_cmnds
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/update_e3sm_tests.py
  src/share/timing/ChangeLog
  src/share/timing/gptl.h
  src/share/timing/private.h
Labels: in progress

#2440 Add support for stampede2-skx and stampede2-knl.
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
Labels: in progress

#2444 Use --no-logging in call to checkout_externals
  scripts/lib/CIME/provenance.py
Labels: cesm-only, in progress, tp: CIMElib, ty: Bug Fix

#2460 Update casename restrictions
  doc/source/users_guide/create-a-case.rst
  scripts/lib/CIME/case/case_clone.py
  scripts/lib/CIME/utils.py
Labels: in progress

#2462 Support renamed glimmer-cism directory; add README files to SourceMods directories
  scripts/Tools/Makefile
  scripts/lib/CIME/case/case.py
Labels: in progress

#2464 Fix env_mach_specific.sh file when module init is None
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2461 Remove logdir
  doc/source/users_guide/running-a-case.rst
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/utils.py
  src/drivers/mct/cime_config/config_component.xml
Labels: in progress

#2468 add model doi url to seq_infodata and to cpl history global attributes
  src/drivers/mct/cime_config/config_component_cesm.xml
  src/drivers/mct/cime_config/config_component_e3sm.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/main/seq_hist_mod.F90
  src/drivers/mct/main/seq_io_mod.F90
  src/drivers/mct/shr/seq_infodata_mod.F90
Labels: in progress

#2465 Fix totalpes
  config/cesm/machines/config_batch.xml
  scripts/create_test
  scripts/fortran_unit_testing/run_tests.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/test_utils.py
  scripts/manage_pes
  scripts/manage_testlists
  src/drivers/mct/cime_config/config_component.xml
Labels: in progress

#2475 Transition CIME to using a custom util for copying files.
  scripts/lib/CIME/BuildTools/configure.py
  scripts/lib/CIME/SystemTests/eri.py
  scripts/lib/CIME/SystemTests/err.py
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_clone.py
  scripts/lib/CIME/case/case_cmpgen_namelists.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/case/case_st_archive.py
  scripts/lib/CIME/case/check_input_data.py
  scripts/lib/CIME/case/preview_namelists.py
  scripts/lib/CIME/get_timing.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/locked_files.py
  scripts/lib/CIME/user_mod_support.py
  scripts/lib/CIME/utils.py
  scripts/lib/CIME/wait_for_tests.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2479 Fix test_scheduler's computation of procs needed for a test
  scripts/lib/CIME/test_scheduler.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2482 add a warning
  scripts/lib/CIME/XML/testlist.py
Labels: in progress

#2481 Cid decesm
  scripts/lib/CIME/Servers/ftp.py
  scripts/lib/CIME/Servers/gftp.py
  scripts/lib/CIME/Servers/svn.py
  scripts/lib/CIME/Servers/wget.py
  scripts/lib/CIME/case/check_input_data.py
Labels: in progress

#2486 Nodefail fix
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/test_scheduler.py
Labels: in progress

#2487 Simple compare improvement
  scripts/lib/CIME/case/case_cmpgen_namelists.py
  scripts/lib/CIME/simple_compare.py
Labels: in progress

#2470 St archive test
  config/cesm/config_archive.xml
  config/cesm/machines/template.st_archive
  config/e3sm/config_archive.xml
  config/e3sm/machines/template.st_archive
  config/xml_schemas/config_archive.xsd
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/XML/archive.py
  scripts/lib/CIME/XML/archive_base.py
  scripts/lib/CIME/XML/env_archive.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_st_archive.py
  scripts/tests/scripts_regression_tests.py
  src/drivers/mct/cime_config/config_archive.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
Labels: in progress

#2489 dont access server if you dont need any data
  scripts/lib/CIME/case/check_input_data.py
Labels: in progress

#2494 Fix for testreporter.py
  scripts/lib/CIME/XML/test_reporter.py
Labels: in progress

#2498 wait_for_tests needs to upload case2 logs if there are some
  scripts/Tools/wait_for_tests
  scripts/lib/CIME/wait_for_tests.py
Labels: e3sm-only, tp: CIMElib, tp: script tools

#2499 Match entire string for XML attribute selectors for env_mach_specific
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2502 Testreporter fix.
  scripts/lib/CIME/XML/test_reporter.py
Labels: in progress

#2503 Remove manage_testlist
  doc/source/users_guide/testing.rst
  scripts/manage_testlists
Labels: in progress

#2195 exp(1/3) is identically 1
  src/share/util/shr_flux_mod.F90
Labels: in progress, ty: Bug Fix
