Repository ESMCI/cime, pull requests merged in 2018-08, with the labels that each got.

#2740 For inputdata servers make it so key members are always defined.
  scripts/lib/CIME/Servers/ftp.py
  scripts/lib/CIME/Servers/svn.py
  scripts/lib/CIME/Servers/wget.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2743 Jgfouca/branch for acme split 2018 08 08
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/config_grids.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/syslog.summit
  config/e3sm/tests.py
  config/xml_schemas/config_compilers_v2.xsd
  scripts/Tools/Makefile
  scripts/Tools/jenkins_generic_job
  scripts/Tools/wait_for_tests
  scripts/Tools/xmlquery
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/test_status.py
  scripts/lib/CIME/utils.py
  scripts/lib/CIME/wait_for_tests.py
  scripts/lib/get_tests.py
  scripts/lib/jenkins_generic_job.py
  scripts/tests/scripts_regression_tests.py
  src/drivers/mct/cime_config/config_component_e3sm.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/seq_diag_mct.F90
  src/drivers/mct/main/seq_map_mod.F90
  src/drivers/mct/shr/seq_comm_mct.F90
  src/drivers/mct/shr/seq_infodata_mod.F90
  src/share/util/mct_mod.F90
  src/share/util/shr_const_mod.F90
  src/share/util/shr_reprosum_mod.F90
  src/share/util/shr_taskmap_mod.F90
Labels: in progress, tp: CIMElib, tp: script tools, ty: enhancement

#2745 Do a better job of handling exceptions in sub-phases of run
  config/config_tests.xml
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/get_tests.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress, tp: CIMElib, ty: Bug Fix, ty: enhancement

#2744 Add BFAIL in more contexts when doing baseline comparisons
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/compare_test_results.py
  scripts/lib/CIME/hist_utils.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2742 updates for compatibility with XML to html tools
  scripts/lib/CIME/XML/component.py
  scripts/lib/CIME/XML/compsets.py
  scripts/lib/CIME/XML/machines.py
  src/components/data_comps/docn/cime_config/config_component.xml
  src/drivers/mct/cime_config/config_component.xml
Labels: in progress, maint-5.6_bugfix

#2750 Disable problematic task-node output by default
  scripts/Tools/Makefile
  src/build_scripts/buildlib.csm_share
  src/drivers/mct/shr/seq_comm_mct.F90
Labels: in progress, tp: drv mct, ty: Bug Fix

#2753 Pgi lapack
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
Labels: in progress

#2755 Extract code for creating a test suite-specific cs.status script
  scripts/lib/CIME/cs_status_creator.py
  scripts/lib/CIME/test_scheduler.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2759 DAE test improve
  scripts/data_assimilation/da_no_data_mod.sh
  scripts/lib/CIME/SystemTests/dae.py
  src/components/data_comps/dwav/mct/wav_comp_mct.F90
Labels: in progress, ty: Bug Fix, ty: enhancement

#2761 Allow TestStatus file to be copied into baselines
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/test_scheduler.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2751 New resume method
  src/components/data_comps/desp/desp_comp_mod.F90
  src/components/data_comps/desp/mct/esp_comp_mct.F90
  src/drivers/mct/cime_config/testdefs/testlist_drv.xml
  src/drivers/mct/cime_config/testdefs/testmods_dirs/drv/multi_driver/shell_commands
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/component_mod.F90
  src/drivers/mct/main/component_type_mod.F90
  src/drivers/mct/main/seq_rest_mod.F90
  src/drivers/mct/shr/CMakeLists.txt
  src/drivers/mct/shr/seq_cdata_mod.F90
  src/drivers/mct/shr/seq_infodata_mod.F90
  src/drivers/mct/shr/seq_pauseresume_mod.F90
Labels: in progress, ty: enhancement

#2763 Propagate --project value to CHARGE_ACCOUNT
  scripts/lib/CIME/case/case.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2765 Update DWAV model
  scripts/data_assimilation/da_no_data_mod.sh
  src/components/data_comps/dwav/mct/wav_comp_mct.F90
  src/drivers/mct/cime_config/testdefs/testmods_dirs/drv/multi_driver/shell_commands
Labels: in progress, ty: Bug Fix

#2768 Dont allow zero ntasks nthrds
  scripts/lib/CIME/XML/env_mach_pes.py
Labels: in progress

#2774 Fix documentation for histaux_r2x namelist variable
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/shr/seq_infodata_mod.F90
Labels: maint-5.6_bugfix, tp: documentation, tp: drv mct, ty: Bug Fix

#2777 Fix DAE test for scripts_regression_tests
  scripts/data_assimilation/da_no_data_mod.sh
  scripts/lib/CIME/SystemTests/dae.py
  scripts/lib/get_tests.py
Labels: in progress, ty: Bug Fix

#2775 Add options to cs.status to allow just summarizing failures
  scripts/Tools/cimeteststatus
  scripts/Tools/cs.status
  scripts/lib/CIME/cs_status.py
  scripts/lib/CIME/cs_status_creator.py
  scripts/lib/CIME/test_status.py
  scripts/lib/CIME/tests/test_cs_status.py
  scripts/lib/cs.status.template
  scripts/lib/six_additions.py
Labels: in progress, tp: script tools, tp: system tests, ty: enhancement

#2780 Make a new grid to ensure ADWAV works with f19_f19
  config/e3sm/config_grids.xml
  scripts/lib/get_tests.py
Labels: in progress, tp: config, tp: system tests, ty: Bug Fix

#2784 Rewrite array code as loops to appease NAG
  src/share/util/mct_mod.F90
Labels: in progress

#2785 Fix use of test_utils
  scripts/create_test
Labels: CRITICAL, tp: system tests, ty: Bug Fix

#2789 Do not report BFAIL for a test that is missing a file
  scripts/lib/CIME/hist_utils.py
Labels: in progress

#2794 Fix pruning of test_hists with refcase in their name
  scripts/lib/CIME/hist_utils.py
Labels: in progress, tp: system tests, ty: Bug Fix
