Repository ESMCI/cime, pull requests merged in 2018-02, with the labels that each got.

#2288 Test compset vs alias
  scripts/tests/scripts_regression_tests.py
Labels: in progress

#2283 move orb year settings for 1850 out of user mods
  src/drivers/mct/cime_config/buildnml
  src/drivers/mct/cime_config/config_component_cesm.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
Labels: in progress

#2292 Leverage env command options to assist parsing
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: CRITICAL, in progress, tp: CIMElib, ty: Bug Fix

#2293 find component for query_config --components
  scripts/query_config
Labels: in progress

#2298 Make get_components return None instead of fail
  scripts/lib/CIME/XML/files.py
Labels: in progress, tp: tools, ty: Bug Fix

#2299 Update components' communicator initialization
  src/drivers/mct/shr/seq_comm_mct.F90
Labels: in progress, tp: drv mct, ty: Bug Fix, ty: enhancement

#2306 Fix bug when providing -p PROJECT flag to create_test
  scripts/lib/CIME/test_scheduler.py
Labels: in progress, tp: CIMElib, tp: script tools, ty: Bug Fix

#2309 add xml support for inputdata server
  config/cesm/config_files.xml
  config/cesm/config_inputdata.xml
  config/e3sm/config_files.xml
  config/e3sm/config_inputdata.xml
  config/xml_schemas/config_inputdata.xsd
  scripts/Tools/check_input_data
  scripts/lib/CIME/XML/inputdata.py
  scripts/lib/CIME/check_input_data.py
Labels: in progress

#2310 Swap command cannot be batched together.
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2305 add support for provenance in cesm
  scripts/lib/CIME/case.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/utils.py
Labels: cesm-only, in progress

#2311 add support for ftp and wget
  config/cesm/config_inputdata.xml
  scripts/Tools/check_input_data
  scripts/lib/CIME/Servers/ftp.py
  scripts/lib/CIME/Servers/generic_server.py
  scripts/lib/CIME/Servers/svn.py
  scripts/lib/CIME/Servers/wget.py
  scripts/lib/CIME/XML/inputdata.py
  scripts/lib/CIME/check_input_data.py
Labels: in progress

#2300 Catch more errors in the testlist schema, remove generic GSW DATM_MODE ignore scripts/cases
  .gitignore
  config/xml_schemas/testlist.xsd
  src/components/data_comps/datm/cime_config/config_component.xml
Labels: in progress, tp: user interface

#2314 Change subtree split method
  scripts/lib/e3sm_cime_mgmt.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2285 Refactor _get_datenames to count the correct number of cpl.r files
  scripts/lib/CIME/case_setup.py
  scripts/lib/CIME/case_st_archive.py
Labels: tp: CIMElib, tp: script tools, tp: tools, ty: Bug Fix

#2315 Add comment pes file
  config/xml_schemas/env_mach_pes.xsd
  scripts/lib/CIME/XML/env_mach_pes.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/XML/pes.py
  scripts/lib/CIME/case.py
Labels: in progress

#2317 New allow_error field for module system
  config/e3sm/machines/config_machines.xml
  config/xml_schemas/env_mach_specific.xsd
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2318 Update esmf module for edison.nersc.gov.
  config/cesm/machines/config_machines.xml
Labels: in progress

#2319 Big upgrade to scripts_regression_tests argument handling
  scripts/tests/scripts_regression_tests.py
Labels: in progress, tp: script tools, ty: enhancement

#2316 add supported flag to testlist.xml
  config/xml_schemas/testlist.xsd
  scripts/lib/CIME/XML/testlist.py
  scripts/lib/CIME/case.py
Labels: in progress

#2290 redo orb_year_defaults for cesm only
  src/drivers/mct/cime_config/buildnml
  src/drivers/mct/cime_config/config_component_cesm.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
Labels: in progress

#2323 Cleanup xml
  scripts/lib/CIME/XML/namelist_definition.py
  src/drivers/mct/cime_config/config_component.xml
Labels: in progress

#2321 supported attribute is string
  scripts/lib/CIME/XML/testlist.py
Labels: in progress

#2324 add travis_ci testing
  .travis.yml
  scripts/Tools/code_checker
  scripts/lib/CIME/BuildTools/makemacroswriter.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/code_checker.py
  scripts/lib/CIME/wait_for_tests.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress

#2320 Auto-regen batch files in case_submit.
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case_setup.py
  scripts/lib/CIME/case_submit.py
  scripts/lib/CIME/check_lockedfiles.py
Labels: in progress, tp: CIMElib, tp: script tools, ty: Discussion, ty: enhancement

#2325 Report lock file info as debug output
  scripts/lib/CIME/check_lockedfiles.py
Labels: in progress, tp: CIMElib

#2326 Refactor handling of small jobs
  config/cesm/machines/config_batch.xml
  config/cesm/machines/template.case.run
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/template.case.run
  config/xml_schemas/config_batch.xsd
  scripts/Tools/preview_run
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case.py
Labels: in progress, tp: CIMElib, tp: config, tp: script tools, ty: enhancement
