Repository ESMCI/cime, pull requests merged in 2018-03, with the labels that each got.

#2327 Reinstate ability to select queue by num tasks
  config/cesm/machines/config_batch.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_batch.xsd
  config/xml_schemas/config_batch.xsd
  config/xml_schemas/env_batch.xsd
  scripts/create_test
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case.py
Labels: in progress, tp: CIMElib, tp: config, ty: enhancement

#2333 For Travis-CI build: kick off build on master whenever it's pushed
  .travis.yml
Labels: in progress, tp: unit tests, ty: enhancement

#2335 add queue attribute (small cheyenne jobs go to share queue)
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_machines.xml
  config/xml_schemas/config_batch.xsd
  config/xml_schemas/config_machines.xsd
  config/xml_schemas/env_batch.xsd
  config/xml_schemas/env_mach_specific.xsd
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/case.py
  scripts/lib/CIME/case_run.py
  scripts/lib/CIME/case_st_archive.py
Labels: in progress

#2339 Env batch cleanup
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case.py
  scripts/lib/CIME/case_submit.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/utils.py
Labels: in progress

#2341 Mpirun depends on queue
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_machines.xml
  scripts/Tools/preview_run
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/case.py
  scripts/lib/CIME/case_run.py
Labels: in progress

#2338 Py regex kdr
  config/cesm/config_archive.xml
  config/config_headers.xml
  config/e3sm/config_archive.xml
  scripts/lib/CIME/case_st_archive.py
  src/components/data_comps/datm/cime_config/config_archive.xml
  src/components/data_comps/dice/cime_config/config_archive.xml
  src/components/data_comps/dlnd/cime_config/config_archive.xml
  src/components/data_comps/docn/cime_config/config_archive.xml
  src/components/data_comps/drof/cime_config/config_archive.xml
  src/components/data_comps/dwav/cime_config/config_archive.xml
  src/drivers/mct/cime_config/config_archive.xml
Labels: in progress

#2345 documentation updates for user customization
  doc/source/conf.py
  doc/source/index.rst
  doc/source/misc_tools/ect.rst
  doc/source/misc_tools/index.rst
  doc/source/users_guide/cime-internals.rst
  doc/source/users_guide/creating-new-compsets.rst
  doc/source/users_guide/index.rst
  doc/source/users_guide/introduction-and-overview.rst
  src/drivers/mct/cime_config/config_component.xml
  src/drivers/mct/cime_config/config_component_cesm.xml
Labels: in progress

#2346 Add a CONTRIBUTING file
  CONTRIBUTING.md
Labels: in progress, tp: documentation, ty: enhancement

#2347 Mfdeakin sandia/st archive/encapsulate datetime
  scripts/lib/CIME/SystemTests/ldsta.py
  scripts/lib/CIME/case_st_archive.py
  scripts/lib/CIME/date.py
Labels: in progress

#2354 modify regex for hobart to work on compute nodes
  config/cesm/machines/config_machines.xml
Labels: in progress

#2355 Add ability to xmlquery derived attributes
  scripts/Tools/xmlchange
  scripts/Tools/xmlquery
  scripts/lib/CIME/case.py
Labels: tp: script tools, tp: user interface, ty: enhancement

#2356 add stack size modifier to hobart
  config/cesm/machines/config_machines.xml
Labels: in progress

#2357 Jgfouca/branch for acme split 2018 03 13
  .gitignore
  config/e3sm/allactive/config_compsets.xml
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/config_grids.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/syslog.anvil
  config/e3sm/machines/syslog.cetus
  config/e3sm/machines/syslog.cori-haswell
  config/e3sm/machines/syslog.cori-knl
  config/e3sm/machines/syslog.edison
  config/e3sm/machines/syslog.mira
  config/e3sm/machines/syslog.theta
  config/e3sm/machines/syslog.titan
  config/e3sm/testmods_dirs/allactive/clm/bgcexp/user_nl_clm
  config/e3sm/testmods_dirs/allactive/clm/bgcexp/xmlchange_cmnds
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/XML/pes.py
  scripts/lib/jenkins_generic_job.py
  scripts/lib/update_e3sm_tests.py
  scripts/tests/scripts_regression_tests.py
  src/drivers/mct/cime_config/config_component_e3sm.xml
Labels: in progress

#2344 Provide infrastructure to allow SCM to run with SE dycore
  src/share/streams/shr_dmodel_mod.F90
  src/share/util/shr_scam_mod.F90
Labels: in progress, tp: data models, tp: src shr, ty: enhancement

#2359 Allow custom batch directive prefixes
  config/cesm/machines/config_batch.xml
  config/e3sm/machines/config_batch.xml
  config/xml_schemas/config_batch.xsd
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2352 Improve create_test error message
  scripts/lib/update_e3sm_tests.py
Labels: acme-only, tp: CIMElib, tp: user interface

#2364 Move example of query_config to introduction
  doc/source/users_guide/case-basics.rst
  doc/source/users_guide/introduction-and-overview.rst
Labels: in progress, tp: documentation, ty: enhancement

#2365 Rename and reorg upper level contents
  doc/source/build_cpl/index.rst
  doc/source/data_models/index.rst
  doc/source/driver_cpl/index.rst
  doc/source/index.rst
  doc/source/users_guide/index.rst
  doc/source/what_cime/index.rst
Labels: in progress, tp: documentation, ty: enhancement

#2367 More updates to e3sm cime mgmt
  scripts/Tools/e3sm_cime_merge
  scripts/Tools/e3sm_cime_split
  scripts/lib/e3sm_cime_mgmt.py
Labels: acme-only, in progress, tp: script tools, ty: enhancement

#2366 ignore files beginning in test_
  scripts/Tools/mkSrcfiles
Labels: in progress

#2369 Support full matching restrictions for batch directives
  config/xml_schemas/config_batch.xsd
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress, tp: CIMElib, tp: user interface, ty: enhancement

#2371 Update to newer version of cprnc on hobart.
  config/cesm/machines/config_machines.xml
Labels: cesm-only, in progress, tp: config, ty: enhancement

#2372 Order e3sm test list by runtime
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/test_scheduler.py
Labels: acme-only, in progress, tp: CIMElib, ty: enhancement

#2373 Fix skip-pnl for tests
  config/cesm/machines/template.case.test
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/template.case.test
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case_run.py
  scripts/lib/CIME/case_test.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress, tp: CIMElib, tp: script tools, ty: Bug Fix

#2370 Update key concepts documentation
  doc/source/users_guide/introduction-and-overview.rst
Labels: in progress, tp: documentation

#2380 Remove old pointclm directory
  scripts/Tools/pointclm/README
  scripts/Tools/pointclm/makepointdata.py
  scripts/Tools/pointclm/pointCLM.py
  scripts/Tools/pointclm/post_process.py
  scripts/Tools/pointclm/site_fullrun.py
Labels: in progress, tp: script tools, ty: enhancement

#2378 Compare two case setup
  scripts/lib/CIME/SystemTests/dae.py
  scripts/lib/CIME/SystemTests/eri.py
  scripts/lib/CIME/SystemTests/erp.py
  scripts/lib/CIME/SystemTests/mcc.py
  scripts/lib/CIME/SystemTests/nck.py
  scripts/lib/CIME/SystemTests/ncr.py
  scripts/lib/CIME/SystemTests/pea.py
  scripts/lib/CIME/SystemTests/pem.py
  scripts/lib/CIME/SystemTests/pet.py
  scripts/lib/CIME/SystemTests/pre.py
  scripts/lib/CIME/SystemTests/seq.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/case.py
  scripts/lib/CIME/tests/case_fake.py
Labels: in progress

#2383 Add an A and X compset test to aux_cime_baselines.
  src/drivers/mct/cime_config/testdefs/testlist_drv.xml
Labels: in progress

#2384 cleanup acme -> e3sm references in rst documentation
  doc/source/data_models/data-ocean.rst
  doc/source/users_guide/adding-cases.rst
  doc/source/users_guide/building-a-case.rst
  doc/source/users_guide/cime-internals.rst
  doc/source/users_guide/porting-cime.rst
  doc/source/users_guide/testing.rst
  doc/source/xml_files/drivers.rst
  doc/source/xml_files/e3sm.rst
  doc/source/xml_files/index.rst
  doc/tools_autodoc.cfg
Labels: e3sm-only, in progress, tp: documentation

#2374 Update MCT to 2.10rc2
  src/externals/mct/README
  src/externals/mct/doc/mct_APIs.tex
  src/externals/mct/mct/m_Rearranger.F90
Labels: in progress, tp: drv mct, tp: externals, ty: enhancement

#2392 Deccsmize
  src/drivers/mct/cime_config/config_component.xml
  src/drivers/mct/cime_config/config_component_cesm.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/shr/seq_comm_mct.F90
  src/drivers/mct/shr/seq_timemgr_mod.F90
Labels: in progress

#2396 Cannot combine soft operations.
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: in progress, tp: CIMElib, ty: Bug Fix

#2400 Py3 fix
  scripts/lib/CIME/XML/env_batch.py
Labels: in progress

#2398 Allow case_diff to work on cases that are not tests
  scripts/Tools/case_diff
Labels: in progress, tp: script tools, ty: Bug Fix

#2404 Only set and check glcrun_avg_alarm if glc_prognostic is true
  src/drivers/mct/main/cime_comp_mod.F90
Labels: in progress, tp: drv mct, ty: Bug Fix

#2386 Add unofficial support for shell version of case.run batch script
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/template.case.run.sh
  scripts/Tools/preview_run
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_run.py
Labels: e3sm-only, in progress, tp: CIMElib, tp: script tools, tp: user interface, ty: enhancement

#2405 Do not make unnecessary env_batch jobs or batch job scripts
  scripts/Tools/preview_run
  scripts/create_test
  scripts/fortran_unit_testing/run_tests.py
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_clone.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/case/case_submit.py
  scripts/lib/CIME/provenance.py
Labels: tp: CIMElib, tp: script tools, ty: enhancement
