Repository ESMCI/cime, pull requests merged in 2018-12, with the labels that each got.

#2934 Correct timer merge issue
  src/share/timing/perf_mod.F90
Labels: in progress

#2925 _PNETCDF needs to be defined in csm_share build
  scripts/Tools/Makefile
Labels: in progress

#2943 Update fv1.9x2.5,gx1v7 grids
  config/cesm/config_grids.xml
Labels: in progress

#2944 fix issues found in cesm testing
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/case/case.py
  scripts/tests/scripts_regression_tests.py
Labels: in progress

#2946 Minor fix for e3sm_cime_mgmt
  scripts/lib/e3sm_cime_mgmt.py
Labels: e3sm-only, in progress, tp: script tools, ty: Bug Fix

#2941 Mlevy/update esmf in mapping master
  tools/mapping/gen_mapping_files/gen_ESMF_mapping_file/create_ESMF_map.sh
Labels: in progress

#2940 Mlevy/update esmf in mapping maint5.6
  tools/mapping/gen_mapping_files/gen_ESMF_mapping_file/create_ESMF_map.sh
Labels: in progress

#2938 do not allow trailing / in filename
  scripts/lib/CIME/utils.py
Labels: in progress

#2948 Improve error/exception handling throughout CIME
  scripts/Tools/case.build
  scripts/Tools/case_diff
  scripts/Tools/testreporter.py
  scripts/Tools/xmlquery
  scripts/create_newcase
  scripts/lib/CIME/Servers/ftp.py
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/XML/component.py
  scripts/lib/CIME/XML/env_batch.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/XML/machines.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_clone.py
  scripts/lib/CIME/case/case_cmpgen_namelists.py
  scripts/lib/CIME/case/case_setup.py
  scripts/lib/CIME/case/case_submit.py
  scripts/lib/CIME/case/case_test.py
  scripts/lib/CIME/compare_namelists.py
  scripts/lib/CIME/namelist.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/CIME/tests/SystemTests/test_system_tests_compare_two.py
  scripts/lib/CIME/tests/test_user_mod_support.py
  scripts/lib/CIME/user_mod_support.py
  scripts/lib/CIME/utils.py
  scripts/lib/CIME/wait_for_tests.py
  scripts/lib/e3sm_cime_mgmt.py
  scripts/lib/get_tests.py
  scripts/query_config
  scripts/tests/scripts_regression_tests.py
  tools/load_balancing_tool/load_balancing_submit.py
Labels: in progress, tp: CIMElib, ty: enhancement

#2951 Fix nag & pgi CAM COSP build
  scripts/Tools/Makefile
Labels: in progress

#2958 Jedwards/maint 5.6merge
  ChangeLog
  config/cesm/config_grids.xml
  scripts/Tools/Makefile
  scripts/lib/CIME/utils.py
Labels: in progress

#2956 improve the logic of the continue run check
  scripts/lib/CIME/case/case_submit.py
Labels: in progress

#2960 List mpi-serial's include directory before any system-level includes
  CMakeLists.txt
Labels: in progress, maint-5.6_bugfix, tp: unit tests, ty: Bug Fix

#2961 cd to correct directory after running create_clone
  doc/source/users_guide/cloning-a-case.rst
Labels: in progress, maint-5.6_bugfix, tp: documentation, ty: Bug Fix
