Repository ESMCI/cime, pull requests merged in 2019-04, with the labels that each got.

#3059 Make FIELDLIST message more informative
  scripts/lib/CIME/hist_utils.py
Labels: tp: system tests, ty: enhancement

#3076 maint-5.6 archive_metadata update
  scripts/Tools/archive_metadata
Labels: cesm-only, tp: script tools, ty: Bug Fix

#3055 Introduces a new stub IAC
  config/cesm/config_files.xml
  config/cesm/config_grids.xml
  config/e3sm/config_files.xml
  config/e3sm/config_grids.xml
  config/xml_schemas/entry_id_base_version3.xsd
  scripts/Tools/Makefile
  scripts/Tools/archive_metadata
  scripts/Tools/case.build
  scripts/Tools/xmlconvertors/config_pes_converter.py
  scripts/Tools/xmlconvertors/grid_xml_converter.py
  scripts/lib/CIME/XML/grids.py
  scripts/lib/CIME/case/case.py
  src/components/stub_comps/siac/cime_config/buildlib
  src/components/stub_comps/siac/cime_config/buildnml
  src/components/stub_comps/siac/cime_config/config_component.xml
  src/components/stub_comps/siac/mct/iac_comp_mct.F90
  src/drivers/mct/cime_config/config_component.xml
  src/drivers/mct/cime_config/config_component_e3sm.xml
  src/drivers/mct/cime_config/config_compsets.xml
  src/drivers/mct/cime_config/config_pes.xml
  src/drivers/mct/cime_config/namelist_definition_drv.xml
  src/drivers/mct/cime_config/namelist_definition_modelio.xml
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/component_mod.F90
  src/drivers/mct/main/component_type_mod.F90
  src/drivers/mct/main/prep_atm_mod.F90
  src/drivers/mct/main/prep_iac_mod.F90
  src/drivers/mct/main/prep_lnd_mod.F90
  src/drivers/mct/main/seq_frac_mct.F90
  src/drivers/mct/main/seq_hist_mod.F90
  src/drivers/mct/main/seq_rest_mod.F90
  src/drivers/mct/shr/seq_comm_mct.F90
  src/drivers/mct/shr/seq_flds_mod.F90
  src/drivers/mct/shr/seq_infodata_mod.F90
  src/drivers/mct/shr/seq_timemgr_mod.F90
Labels: tp: drv mct, tp: stub models, ty: enhancement

#3063 Add NLDAS grid for CTSM and MOSART
  config/cesm/config_grids.xml
Labels: cesm-only, tp: config, ty: enhancement

#3084 Allow specific tests to ignore field list differences
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/SystemTests/system_tests_compare_two.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/tests/SystemTests/test_system_tests_compare_two.py
Labels: in progress, tp: system tests, ty: enhancement

#3086 Fix ne0CONUSne30x8 grids
  config/cesm/config_grids.xml
  config/cesm/config_grids_common.xml
  config/cesm/config_grids_mct.xml
Labels: in progress

#3088 properly link nag f90
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_compilers.xml
  scripts/Tools/Makefile
  src/components/xcpl_comps/xshare/mct/dead_mod.F90
Labels: in progress

#3089 Updatemodulescheyenne
  config/cesm/machines/config_machines.xml
Labels: in progress

#3091 fix for edison
  config/cesm/machines/config_machines.xml
Labels: in progress

#3095 better error reporting for refcase errors
  scripts/lib/CIME/case/check_input_data.py
Labels: in progress

#3096 Jgfouca/branch for acme split 2019 04 29
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/syslog.anvil
  config/e3sm/tests.py
  scripts/Tools/Makefile
  scripts/lib/CIME/provenance.py
Labels: in progress

#3093 Change DATM_CLMNCEP_YR_ALIGN for present-day compsets
  src/components/data_comps/datm/cime_config/config_component.xml
Labels: in progress, tp: data models, ty: enhancement

#3098 Add NLDAS2 datm forcing option
  src/components/data_comps/datm/cime_config/config_component.xml
  src/components/data_comps/datm/cime_config/namelist_definition_datm.xml
Labels: in progress, tp: data models, ty: enhancement
