Repository ESMCI/cime, pull requests merged in 2019-03, with the labels that each got.

#3023 Pio1 merge
  src/externals/pio1/pio/pio_types.F90
  src/externals/pio1/pio/piodarray.F90.in
  src/externals/pio1/pio/pionfput_mod.F90.in
Labels: in progress

#3021 Jgfouca/branch for acme split 2019 02 28
  config/e3sm/allactive/config_pesall.xml
  config/e3sm/config_grids.xml
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/config_pio.xml
  config/e3sm/tests.py
  config/xml_schemas/config_compilers_v2.xsd
  scripts/Tools/Makefile
  scripts/create_test
  scripts/lib/CIME/BuildTools/cmakemacroswriter.py
  scripts/lib/CIME/BuildTools/macrowriterbase.py
  scripts/lib/CIME/BuildTools/makemacroswriter.py
  scripts/lib/CIME/SystemTests/tsc.py
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/bless_test_results.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case_st_archive.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/get_tests.py
  scripts/tests/scripts_regression_tests.py
  src/build_scripts/buildlib.kokkos
  src/externals/pio2/ctest/CTestEnvironment-nwscla.cmake
  src/externals/pio2/src/clib/pio_nc.c
  src/externals/pio2/tests/cunit/test_async_multi2.c
  src/externals/pio2/tests/cunit/test_darray_2sync.c
  src/externals/pio2/tests/general/ncdf_simple_tests.F90.in
  src/share/timing/gptl.c
  src/share/timing/private.h
Labels: in progress

#3018 Checksum inputdata
  config/cesm/config_inputdata.xml
  scripts/Tools/check_input_data
  scripts/lib/CIME/Servers/ftp.py
  scripts/lib/CIME/Servers/wget.py
  scripts/lib/CIME/XML/inputdata.py
  scripts/lib/CIME/case/check_input_data.py
Labels: in progress

#3030 Update CAM-SE grids
  config/cesm/config_grids.xml
  config/cesm/config_grids_common.xml
  config/cesm/config_grids_mct.xml
Labels: in progress

#3038 Chksum fixes maint 5.6
  scripts/lib/CIME/Servers/ftp.py
  scripts/lib/CIME/Servers/gftp.py
  scripts/lib/CIME/Servers/svn.py
  scripts/lib/CIME/Servers/wget.py
  scripts/lib/CIME/case/check_input_data.py
Labels: in progress

#3024 Jedwards/standard makefile args
  config/cesm/config_grids_nuopc.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
  scripts/Tools/Makefile
  scripts/Tools/get_standard_makefile_args
  scripts/lib/CIME/build.py
  scripts/lib/CIME/buildlib.py
  scripts/lib/CIME/case/case.py
  src/build_scripts/buildlib.csm_share
  src/build_scripts/buildlib.gptl
  src/build_scripts/buildlib.mct
  src/build_scripts/buildlib.mpi-serial
  src/build_scripts/buildlib.pio
  src/drivers/mct/cime_config/buildexe
  src/drivers/nuopc/cime_config/buildexe
  src/share/timing/Makefile
Labels: in progress

#3040 Implement 'share' field of test suites
  scripts/create_test
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/get_tests.py
Labels: e3sm-only, in progress, tp: script tools, ty: enhancement

#3042 fix issue with PET and ERP tests
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case.py
  src/build_scripts/buildlib.gptl
Labels: in progress

#3043 Fix ./case.build --clean.
  scripts/lib/CIME/build.py
Labels: tp: CIMElib, ty: Bug Fix

#3045 fix continue run issue for multidriver
  scripts/lib/CIME/case/case_submit.py
Labels: in progress

#3046 Nuopc cmeps
  config/cesm/machines/config_machines.xml
  src/components/data_comps/datm/nuopc/datm_comp_mod.F90
Labels: in progress

#3051 cprnc: allow differences in field lists for time-constant fields
  tools/cprnc/README
  tools/cprnc/compare_vars_mod.F90.in
  tools/cprnc/cprnc.F90
  tools/cprnc/filestruct.F90
  tools/cprnc/run_tests
  tools/cprnc/test_inputs/README
  tools/cprnc/test_inputs/multipleTimes_someTimeless_extra_and_missing.nc
  tools/cprnc/test_inputs/noTime_extra_and_missing.nc
Labels: tp: system tests, ty: Bug Fix
