Repository ESMCI/cime, pull requests merged in 2019-02, with the labels that each got.

#2988 Report missing variables in cprnc
  scripts/lib/CIME/hist_utils.py
  tools/cprnc/README
  tools/cprnc/compare_vars_mod.F90.in
  tools/cprnc/cprnc.F90
  tools/cprnc/filestruct.F90
  tools/cprnc/run_tests
  tools/cprnc/test_inputs/README
  tools/cprnc/test_inputs/control_attributes.nc
  tools/cprnc/test_inputs/control_char.nc
  tools/cprnc/test_inputs/copy_char.nc
  tools/cprnc/test_inputs/diffs_in_attribute.nc
  tools/cprnc/test_inputs/diffs_in_vals_and_extra_and_missing.nc
  tools/cprnc/test_inputs/extra_variables.nc
  tools/cprnc/test_inputs/missing_variables.nc
Labels: tp: system tests, ty: enhancement

#2995 Allow specifying directives to use for an unknown queue
  config/cesm/machines/config_batch.xml
  config/xml_schemas/config_batch.xsd
  scripts/lib/CIME/XML/env_batch.py
Labels: maint-5.6_bugfix, tp: config, ty: Bug Fix

#3003 Fix CIME dashboad regression tests
  scripts/tests/scripts_regression_tests.py
Labels: e3sm-only, tp: unit tests, ty: Bug Fix

#3004 update for stand-alone CMIP6 query outside of a caseroot
  scripts/Tools/archive_metadata
Labels: cesm-only, tp: script tools

#3013 changes to fix cdash testing
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
Labels: in progress

#3012 Fischer/ect doc
  doc/source/misc_tools/ect.rst
Labels: in progress

#3009 Pio2 merge 0c390bf9c
  src/externals/pio2/CMakeLists.txt
  src/externals/pio2/README.md
  src/externals/pio2/cmake/FindNetCDF.cmake
  src/externals/pio2/cmake/LibMPI.cmake
  src/externals/pio2/cmake/mpiexec.nwscla
  src/externals/pio2/configure.ac
  src/externals/pio2/ctest/CTestEnvironment-nwscla.cmake
  src/externals/pio2/ctest/runcdash-nwscla-intel.sh
  src/externals/pio2/doc/Doxyfile.in
  src/externals/pio2/examples/c/darray_async.c
  src/externals/pio2/examples/c/darray_no_async.c
  src/externals/pio2/src/clib/pio.h
  src/externals/pio2/src/clib/pio_darray.c
  src/externals/pio2/src/clib/pio_darray_int.c
  src/externals/pio2/src/clib/pio_getput_int.c
  src/externals/pio2/src/clib/pio_internal.h
  src/externals/pio2/src/clib/pio_msg.c
  src/externals/pio2/src/clib/pio_nc.c
  src/externals/pio2/src/clib/pioc.c
  src/externals/pio2/src/clib/pioc_support.c
  src/externals/pio2/tests/cunit/CMakeLists.txt
  src/externals/pio2/tests/cunit/Makefile.am
  src/externals/pio2/tests/cunit/test_async_multi2.c
  src/externals/pio2/tests/cunit/test_darray.c
  src/externals/pio2/tests/cunit/test_darray_1d.c
  src/externals/pio2/tests/cunit/test_darray_2sync.c
  src/externals/pio2/tests/cunit/test_darray_multi.c
  src/externals/pio2/tests/cunit/test_darray_multivar3.c
  src/externals/pio2/tests/cunit/test_pioc.c
  src/externals/pio2/tests/general/ncdf_simple_tests.F90.in
  src/externals/pio2/tests/general/pio_decomp_tests_1d.F90.in
Labels: in progress

#3015 Fischer/ne30 support
  config/cesm/config_grids.xml
Labels: in progress

#3014 Config grids v2.1
  config/cesm/config_files.xml
  config/cesm/config_grids.xml
  config/cesm/config_grids_common.xml
  config/cesm/config_grids_mct.xml
  config/cesm/config_grids_nuopc.xml
  config/e3sm/config_files.xml
  config/xml_schemas/config_grids_v2.1.xsd
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/XML/grids.py
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/utils.py
  scripts/tests/scripts_regression_tests.py
  src/drivers/nuopc/cime_config/config_component.xml
Labels: in progress

#3019 Batch and resubmit
  scripts/lib/CIME/case/case_submit.py
Labels: in progress

#3020 update NYF CORE2 DROF data stream file.
  src/components/data_comps/drof/cime_config/namelist_definition_drof.xml
Labels: in progress, tp: data models
