Repository ESMCI/cime, pull requests merged in 2019-12, with the labels that each got.

#3316 Fix bug in #3257
  src/drivers/mct/cime_config/namelist_definition_drv.xml
Labels: CRITICAL, maint-5.6_bugfix

#3319 Fixed Empty .cesm_proj file results in a crash.
  scripts/lib/CIME/utils.py
Labels: tp: CIMElib, ty: Bug Fix

#3313 add CESM2 community project experiment types C1, C2, C3, C4, C5
  scripts/Tools/archive_metadata
Labels: cesm-only, tp: script tools

#3332 Add some ideas to the troubleshooting guide
  doc/source/users_guide/troubleshooting.rst
Labels: tp: documentation, ty: enhancement
