Repository ESMCI/cime, pull requests merged in 2019-05, with the labels that each got.

#3099 Allow custom run_exe and run_misc_suffix
  config/xml_schemas/config_machines.xsd
  config/xml_schemas/env_mach_specific.xsd
  doc/source/users_guide/machine.rst
  scripts/fortran_unit_testing/run_tests.py
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/case/case.py
Labels: in progress, tp: CIMElib, ty: enhancement

#3103 dont require optional arguments
  scripts/lib/CIME/XML/env_mach_specific.py
Labels: in progress

#3108 Updates for pleiades
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
Labels: in progress

#3107 send run two TestStatus.log to case1 log
  scripts/lib/CIME/SystemTests/system_tests_common.py
Labels: in progress

#3110 Bring changes to datm Present Day compsets from master to maint-5-6
  src/components/data_comps/datm/cime_config/config_component.xml
Labels: in progress, tp: data models

#3111 Jgfouca/branch for acme split 2019 05 14
  config/e3sm/machines/config_batch.xml
  config/e3sm/machines/config_compilers.xml
  config/e3sm/machines/config_machines.xml
  config/e3sm/machines/config_pio.xml
  scripts/Tools/Makefile
  scripts/lib/CIME/Servers/wget.py
  src/build_scripts/buildlib.kokkos
Labels: in progress

#3112 Add CO2 time-series for CMIP6 future scenarios and three prescribed aerosol CMIP6 future scenarios
  doc/source/users_guide/compsets.rst
  src/components/data_comps/datm/cime_config/config_component.xml
  src/components/data_comps/datm/cime_config/namelist_definition_datm.xml
  src/drivers/mct/cime_config/config_component_cesm.xml
  src/drivers/mct/cime_config/config_compsets.xml
Labels: in progress, maint-5.6_bugfix, tp: data models, ty: enhancement

#3118 Use truncated division operator in SEQ SystemTest for py2+3 compatibility
  scripts/lib/CIME/SystemTests/seq.py
Labels: tp: system tests, ty: Bug Fix

#3115 Provide default for the number of create_test parallel jobs
  config/e3sm/machines/config_machines.xml
  config/xml_schemas/config_machines.xsd
  scripts/lib/CIME/test_scheduler.py
Labels: tp: CIMElib, ty: Bug Fix

#3122 update archive_metadata strip to lstrip
  scripts/Tools/archive_metadata
Labels: cesm-only, maint-5.6_bugfix, tp: script tools, ty: Bug Fix
