Repository ESMCI/cime, pull requests merged in 2019-11, with the labels that each got.

#3292 cleanup env batch
  scripts/create_test
  scripts/lib/CIME/XML/env_batch.py
  scripts/tests/scripts_regression_tests.py
Labels: tp: CIMElib, ty: Bug Fix

#3300 Update location for obtaining pFUnit
  doc/source/users_guide/unit_testing.rst
Labels: tp: documentation, ty: Bug Fix

#3302 Two issues on maint-5.6 for izumi
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
Labels: cesm-only, machine specific, maint-5.6_bugfix, ty: enhancement

#3311 Document the possible need for setting env vars in pFUnit build
  doc/source/users_guide/unit_testing.rst
Labels: tp: documentation

#3315 Fix clean build for CLM
  scripts/Tools/Makefile
  scripts/lib/CIME/build.py
Labels: tp: CIMElib, ty: Bug Fix
