Repository ESMCI/cime, pull requests merged in 2020-07, with the labels that each got.

#3605 Dict has_key is removed in python3
  scripts/lib/CIME/simple_compare.py
Labels: tp: system tests, ty: Bug Fix

#3611 buildlib.cprnc make sure to call cprnc through wrapper
  tools/cprnc/CMakeLists.txt
Labels: tp: CIMElib, ty: Bug Fix

#3622 Fix build clean for e3sm
  scripts/lib/CIME/build.py
  scripts/tests/scripts_regression_tests.py
Labels: tp: CIMElib, ty: Bug Fix

#3632 Remove E3SM CIME subtree managent tools and libraries
  scripts/Tools/e3sm_cime_merge
  scripts/Tools/e3sm_cime_split
  scripts/lib/e3sm_cime_mgmt.py
Labels: e3sm-only

#3634 stampede2 and cori machine updates
  config/cesm/machines/config_machines.xml
Labels: machine specific

#3638 Use SRCROOT instead of CIMEROOT in key places
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/buildlib.py
  scripts/lib/CIME/hist_utils.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/wait_for_tests.py
Labels: e3sm-only

#3642 Fix G_TestBuildSystem test
  scripts/tests/scripts_regression_tests.py
Labels: ty: Bug Fix

#3641 Adding support to the data runoff model for E3SM Cryosphere
  src/components/data_comps_mct/drof/cime_config/config_component.xml
  src/components/data_comps_mct/drof/cime_config/namelist_definition_drof.xml
Labels: in progress, tp: data models
