Repository ESMCI/cime, pull requests merged in 2020-11, with the labels that each got.

#3764 Rename _separate_builds to _user_separate_builds
  scripts/lib/CIME/SystemTests/system_tests_common.py
Labels: tp: CIMElib, ty: Bug Fix

#3767 Add ability to add timings to all build operations for E3SM
  scripts/Tools/case.build
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/build.py
Labels: e3sm-only

#3770 Avoid building CDEPS with CTSM's LILAC
  scripts/lib/CIME/build.py
Labels: tp: CIMElib, ty: enhancement

#3773 e3sm_compile_wrap: New build wrapper for e3sm
  scripts/Tools/e3sm_compile_wrap.py
  scripts/lib/CIME/case/case.py
Labels: e3sm-only

#3774 Remove timing flags for e3sm build
  scripts/Tools/case.build
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/build.py
Labels: e3sm-only

#3754 Update seq_io_write_time to work for CPLHIST run
  src/drivers/mct/main/seq_io_mod.F90
Labels: tp: drv mct, ty: Bug Fix

#3782 More e3sm build upgrades
  scripts/lib/CIME/build.py
  scripts/lib/CIME/provenance.py
Labels: e3sm-only
