Repository ESMCI/cime, pull requests merged in 2020-10, with the labels that each got.

#3729 Add EAM case for 20TR CMIP6 docn component
  src/components/data_comps_mct/docn/cime_config/config_component.xml
Labels: tp: config, tp: data models

#3734 Some updates to E3SM test infrastructure
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/wait_for_tests.py
Labels: e3sm-only

#3736 In MEMLEAK checks, skip first day memory highwater while initializing.
  scripts/lib/CIME/SystemTests/system_tests_common.py
Labels: tp: system tests

#3738 Add a no-submit option to jenkins_generic_job
  scripts/Tools/jenkins_generic_job
Labels: e3sm-only

#3739 Fix current mods test
  config/config_tests.xml
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/case/case_run.py
  scripts/lib/CIME/case/case_st_archive.py
  scripts/lib/CIME/tests/SystemTests/test_system_tests_compare_two.py
  scripts/tests/scripts_regression_tests.py
Labels: ty: Bug Fix

#3737 Wpcoomb change name ccsm cppdefs
  scripts/lib/CIME/build.py
  scripts/lib/CIME/buildlib.py
  src/drivers/mct/cime_config/buildlib_cmake
Labels: tp: CIMElib, ty: enhancement

#3741 jenkins_generic_job: allow user to force turning off success update
  scripts/Tools/jenkins_generic_job
Labels: e3sm-only

#3744 Fix hang in TESTRUNDIFFRESUBMIT
  scripts/lib/CIME/SystemTests/system_tests_common.py
Labels: ty: Bug Fix

#3756 Some build system updates for e3sm
  scripts/Tools/case.build
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/buildlib.py
  src/build_scripts/buildlib.internal_components
  src/build_scripts/buildlib_cmake.internal_components
Labels: e3sm-only

#3759 These changes should have been included in prior cmake PR
  scripts/lib/CIME/SystemTests/system_tests_common.py
Labels: e3sm-only

#3760 Add an error check for separate builds
  scripts/Tools/case.build
Labels: e3sm-only
