Repository ESMCI/cime, pull requests merged in 2020-06, with the labels that each got.

#3558 Add Makefile target to write various flags
  scripts/Tools/Makefile
Labels: tp: script tools, ty: enhancement

#3546 updates for pleiades
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_machines.xml
Labels: ty: Bug

#3583 Use pio1 even for mpi-serial cases in CESM
  config/cesm/machines/config_pio.xml
Labels: cesm-only

#3585 Give the file name that results in the "empty read-only file" error
  scripts/lib/CIME/XML/generic_xml.py
Labels: tp: CIMElib, ty: enhancement

#3589 Clean up screen output & logging in check_input_data
  scripts/lib/CIME/case/check_input_data.py
Labels: tp: CIMElib, ty: enhancement
