Repository ESMCI/cime, pull requests merged in 2020-01, with the labels that each got.

#3340 Implement automatic test traiging in e3sm test infrastructure
  scripts/Tools/jenkins_generic_job
  scripts/Tools/jenkins_script
  scripts/Tools/wait_for_tests
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/provenance.py
  scripts/lib/CIME/wait_for_tests.py
  scripts/lib/jenkins_generic_job.py
  scripts/tests/scripts_regression_tests.py
Labels: e3sm-only

#3354 Wpcoomb/fix misleading output casestatus
  scripts/lib/CIME/build.py
  scripts/lib/CIME/case/case_run.py
Labels: tp: CIMElib, ty: Bug Fix

#3356 Allow writing T-forcing cplhist files even when running with SGLC
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/prep_glc_mod.F90
Labels: maint-5.6_bugfix, tp: drv mct, ty: enhancement

#3364 Fix chmod command in safe_copy
  scripts/lib/CIME/utils.py
Labels: CRITICAL, maint-5.6_bugfix, tp: CIMElib, ty: Bug Fix

#3358 Allow writing T-forcing cplhist files even when running with SGLC (for master)
  src/drivers/mct/main/cime_comp_mod.F90
  src/drivers/mct/main/prep_glc_mod.F90
Labels: tp: drv mct, ty: enhancement
