Repository ESMCI/cime, pull requests merged in 2020-04, with the labels that each got.

#3472 Add SSP*EXT_ for DATM_PRESAERO and DATM_CO2_TSERIES
  src/components/data_comps/datm/cime_config/config_component.xml
Labels: ty: enhancement

#3482 initialize XML variable values to be empty
  scripts/Tools/archive_metadata
Labels: cesm-only, maint-5.6_bugfix, tp: script tools

#3486 Bring back the setting of dlnd strm_domdir and strm_domfil to null
  src/components/data_comps_mct/dlnd/cime_config/namelist_definition_dlnd.xml
Labels: CRITICAL, tp: data models, ty: Bug Fix

#3468 Wpcoomb/user defined env variables
  scripts/lib/CIME/XML/env_mach_specific.py
  scripts/lib/CIME/XML/generic_xml.py
Labels: tp: documentation, ty: enhancement

#3511 case.setup: fix case.setup --clean
  scripts/lib/CIME/case/case_setup.py
  scripts/tests/scripts_regression_tests.py
Labels: tp: CIMElib, ty: Bug Fix
