Repository ESMCI/cime, pull requests merged in 2021-04, with the labels that each got.

#3904 Save Scorpio I/O statistics
  scripts/lib/CIME/provenance.py
Labels: e3sm-only, ty: enhancement

#3917 Generalize build directory paths, and prep for CESM share repository
  scripts/Tools/Makefile
  scripts/lib/CIME/XML/generic_xml.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/buildlib.py
  scripts/lib/CIME/case/case_clone.py
  scripts/lib/CIME/utils.py
  scripts/tests/scripts_regression_tests.py
  src/build_scripts/buildlib.internal_components
  src/build_scripts/buildlib_cmake.internal_components
Labels: ready, ty: enhancement

#3914 Fix create_test --retry when generating baselines
  scripts/create_test
Labels: tp: system tests, ty: Bug Fix

#3930 Allow E3SM to use its versions of coupler and data,stub,x models.
  config/e3sm/config_files.xml
  src/build_scripts/buildlib.csm_share
Labels: tp: CIMElib

#3935 Add support for WAV as primary component
  scripts/lib/CIME/case/case.py
Labels: tp: CIMElib

#3938 Remove "Code review" line from PR template
  .github/PULL_REQUEST_TEMPLATE
Labels: tp: documentation
