Repository ESMCI/cime, pull requests merged in 2021-12, with the labels that each got.

#4132 cprnc should compare NaN
  tools/cprnc/compare_vars_mod.F90.in
  tools/cprnc/run_tests
  tools/cprnc/test_inputs/README
  tools/cprnc/test_inputs/control_floatDoubleNan.nc
  tools/cprnc/test_inputs/diffs_in_nans.nc
Labels: ty: enhancement

#4134 Fix probing machine
  scripts/lib/CIME/XML/machines.py
Labels: ty: Bug Fix, tp: CIMElib

#4128 Fix SSL certification for testing database.
  scripts/lib/CIME/XML/test_reporter.py
Labels: cesm-only

#4137 Update the documentation of --extra-machines-dir
  scripts/create_newcase
Labels: ty: enhancement, tp: CIMElib
