Repository ESMCI/cime, pull requests merged in 2021-01, with the labels that each got.

#3819 Add support for Chrysalis in saving provenance info
  scripts/lib/CIME/provenance.py
Labels: ready

#3824 Better create_test/wait_for_tests integration
  scripts/Tools/cime_bisect
  scripts/Tools/wait_for_tests
  scripts/create_test
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/bless_test_results.py
  scripts/lib/CIME/cs_status.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/CIME/test_status.py
  scripts/lib/CIME/wait_for_tests.py
  scripts/tests/scripts_regression_tests.py
Labels: tp: CIMElib, ty: enhancement

#3829 wait_for_tests: tweak cdash nml compare column
  scripts/lib/CIME/wait_for_tests.py
Labels: e3sm-only

#3840 Fix some documentation of EXEROOT
  doc/source/users_guide/running-a-case.rst
Labels: tp: documentation, ty: Bug Fix
