Repository ESMCI/cime, pull requests merged in 2021-06, with the labels that each got.

#3967 Update climate reproducibility tests
  scripts/lib/CIME/SystemTests/mvk.py
  scripts/lib/CIME/SystemTests/pgn.py
  scripts/lib/CIME/SystemTests/tsc.py
Labels: tp: system tests, ty: Bug Fix

#3982 Allow multiple grids for a component
  config/cesm/config_grids.xml
  config/cesm/config_grids_common.xml
  scripts/lib/CIME/XML/grids.py
  scripts/lib/CIME/nmlgen.py
  scripts/lib/CIME/tests/XML/test_grids.py
Labels: tp: CIMElib, ty: enhancement

#4006 Change cdash upload settings
  scripts/lib/CIME/wait_for_tests.py
  scripts/tests/CTestConfig.cmake
Labels: e3sm-only

#4021 Fix test_reporter for python3
  scripts/lib/CIME/XML/test_reporter.py
Labels: cesm-only

#3789 Greenplanet support
  config/cesm/machines/config_batch.xml
  config/cesm/machines/config_compilers.xml
  config/cesm/machines/config_machines.xml
Labels: cesm-only, tp: config
