Repository ESMCI/cime, pull requests merged in 2021-07, with the labels that each got.

#4027 Additional support for ww3 as a component in the e3sm config file
  config/e3sm/config_files.xml
Labels: e3sm-only

#4028 Adds missing value for desp component
  config/e3sm/config_files.xml
Labels: e3sm-only, tp: config, tp: data models

#4031 Allow a test to have multiple testmods
  scripts/create_clone
  scripts/create_newcase
  scripts/lib/CIME/case/case.py
  scripts/lib/CIME/case/case_clone.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/CIME/test_utils.py
  scripts/lib/CIME/utils.py
  scripts/lib/get_tests.py
Labels: tp: system tests, ty: enhancement

#4035 Update python version check, and load python module on cheyenne
  config/cesm/machines/config_machines.xml
  scripts/Tools/standard_script_setup.py
Labels: ty: Bug Fix

#4038 Fix bugs in climate reproducibility tests
  scripts/lib/CIME/SystemTests/mvk.py
  scripts/lib/CIME/SystemTests/pgn.py
Labels: e3sm-only

#4046 jenkins_generic_job: no reason for this magic config setting here
  scripts/Tools/jenkins_generic_job
  scripts/tests/scripts_regression_tests.py
Labels: e3sm-only

#4052 Ensure Cmake is available for wait_for_tests
  scripts/lib/CIME/wait_for_tests.py
Labels: e3sm-only

#4057 Prepend the casename to mpas component restart file search in st_archive
  scripts/lib/CIME/case/case_st_archive.py
Labels: e3sm-only
