Repository ESMCI/cime, pull requests merged in 2021-11, with the labels that each got.

#3823 More grids for mizuRoute
  config/cesm/config_grids.xml
  config/cesm/config_grids_nuopc.xml
  tools/mapping/gen_mapping_files/gen_ESMF_mapping_file/create_ESMF_map.sh
Labels: ty: enhancement, tp: user interface, ready, cesm-only, tp: config

#4108 Remove documentation sections for pieces no longer included in CIME
  README.md
  doc/source/data_models/data-atm.rst
  doc/source/data_models/data-lnd.rst
  doc/source/data_models/data-model-science.rst
  doc/source/data_models/data-ocean.rst
  doc/source/data_models/data-river.rst
  doc/source/data_models/data-seaice.rst
  doc/source/data_models/data-wave.rst
  doc/source/data_models/design-details.rst
  doc/source/data_models/index.rst
  doc/source/data_models/input-namelists.rst
  doc/source/data_models/input-streams.rst
  doc/source/data_models/introduction.rst
  doc/source/driver_cpl/bit-for-bit-flag.rst
  doc/source/driver_cpl/budgets.rst
  doc/source/driver_cpl/cplug-02.1-figx1.jpg
  doc/source/driver_cpl/design.rst
  doc/source/driver_cpl/driver_threading_control.rst
  doc/source/driver_cpl/grids.rst
  doc/source/driver_cpl/history-and-restarts.rst
  doc/source/driver_cpl/implementation.rst
  doc/source/driver_cpl/index.rst
  doc/source/driver_cpl/initialization-and-restart.rst
  doc/source/driver_cpl/introduction.rst
  doc/source/driver_cpl/multi-instance.rst
  doc/source/driver_cpl/namelist-overview.rst
  doc/source/driver_cpl/time-management.rst
  doc/source/index.rst
  doc/source/users_guide/cime-change-namelist.rst
  doc/source/what_cime/index.rst
Labels: tp: documentation

#4123 Fix broken links in documentation
  doc/source/users_guide/cime-change-namelist.rst
  doc/source/users_guide/grids.rst
  doc/source/users_guide/running-a-case.rst
Labels: tp: documentation, ty: Bug Fix

#4117 add python 3.7.0 module load for izumi (CESM only)
  config/cesm/machines/config_machines.xml
Labels: cesm-only, tp: config

#4127 Cleanup Scorpio I/O performance data in the run directory
  scripts/lib/CIME/provenance.py
Labels: ty: enhancement, e3sm-only
