Repository ESMCI/cime, pull requests merged in 2022-01, with the labels that each got.

#4149 FUNIT needs CIME_NO_CMAKE_MACRO ON for now
  scripts/lib/CIME/SystemTests/funit.py
Labels: tp: system tests, ty: Bug Fix

#4151 Extend throughput and memory checking in baseline tests
  config/xml_schemas/config_machines.xsd
  scripts/Tools/cs.status
  scripts/Tools/jenkins_generic_job
  scripts/lib/CIME/SystemTests/system_tests_common.py
  scripts/lib/CIME/cs_status.py
  scripts/lib/CIME/test_scheduler.py
  scripts/lib/jenkins_generic_job.py
Labels: ty: enhancement

#4155 Remove test_release from test_categories
  scripts/lib/CIME/case/case.py
Labels: tp: CIMElib

#4156 This fixes a number of fails in scripts_regression for e3sm on mappy
  scripts/lib/CIME/tests/base.py
  scripts/lib/CIME/tests/test_sys_grid_generation.py
  scripts/lib/CIME/tests/test_sys_jenkins_generic_job.py
  scripts/lib/CIME/tests/test_sys_test_scheduler.py
Labels: ty: Bug Fix

#4161 Remove the remaining users of config_compilers.xml
  scripts/fortran_unit_testing/run_tests.py
  scripts/lib/CIME/BuildTools/configure.py
  scripts/lib/CIME/SystemTests/funit.py
  scripts/lib/CIME/XML/compilers.py
  scripts/lib/CIME/build.py
  scripts/lib/CIME/tests/test_sys_cmake_macros.py
  scripts/lib/CIME/tests/test_sys_create_newcase.py
  scripts/lib/CIME/tests/test_sys_macro_basic.py
  scripts/lib/CIME/tests/test_sys_make_macros.py
  scripts/lib/CIME/tests/test_sys_unittest.py
  scripts/lib/CIME/tests/utils.py
  tools/cprnc/README
  tools/mapping/gen_domain_files/test_gen_domain.sh
Labels: in progress

#4166 Update tests to get status from new EVV output
  scripts/lib/CIME/SystemTests/mvk.py
  scripts/lib/CIME/SystemTests/pgn.py
  scripts/lib/CIME/SystemTests/tsc.py
Labels: tp: system tests
