Repository ESMCI/cime, pull requests merged in 2023-07, with the labels that each got.

#4445 Fix SLIM testlist name, and tweak the stale bot
  .github/workflows/stale.yml
  CIME/data/config/cesm/config_files.xml
Labels: ty: enhancement, ty: Bug Fix

#4457 Use standard Fortran functions for getting command-line arguments
  tools/mapping/gen_domain_files/INSTALL
  tools/mapping/gen_domain_files/src/gen_domain.F90
Labels: ty: Bug Fix, tp: tools

#4464 Add support for MPASO_USE_PETSC
  CIME/build.py
Labels: e3sm-only
